# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.25.0
import dataclasses
import datetime
from typing import Any, Optional
import uuid


@dataclasses.dataclass()
class SchemaMigration:
    version: str


@dataclasses.dataclass()
class User:
    id: uuid.UUID
    name: Optional[str]
    hashed_password: Optional[str]
    created_at: Optional[datetime.datetime]


@dataclasses.dataclass()
class Verse:
    id: uuid.UUID
    book: Optional[str]
    chapter: Optional[int]
    verse: Optional[int]
    content: str
    embedding: Any
    created_at: Optional[datetime.datetime]
